find_trending_companies:
  description: >
    Search the latest financial news related to the {sector} sector to identify trending companies currently trending. 
    Ensure these are companies that have not been previously selected to maintain novelty in recommendations.
  expected_output: >
    A  list of trending companies in the {sector}, each represented by their name and a short explanation of why they are trending.
  agent: trending_company_finder
  output_file: output/trending_companies.json

research_trending_companies:
  description: >
    For each trending company identified, perform an in-depth online investigation. 
    Analyze their recent performance, news, strategic moves, and future prospects. 
    Summarize your findings in a clear, well-structured report.
  expected_output: >
    A structured report with detailed analysis for each company, including financial performance, news highlights, strengths, weaknesses, and growth outlook.
  agent: financial_researcher
  context:
    - find_trending_companies
  output_file: output/research_report.json

pick_best_company:
  description: >
    Review the research and select the single most promising company for investment.  
    Send a push notification message to the user with a one-line rationale sentence.
    Then justify your selection in a detailed report and explain why other companies were not selected
  expected_output: >
    A report including:
    - The chosen company and a clear rationale
    - A summary of why other companies were excluded
    - The message sent via push notification
  agent: stock_picker
  context:
    - research_trending_companies
  output_file: output/decision.md
